export const products = {
    'products': [{
            "id": 1,
            "name": "camiseta mescla",
            "image": "img_2.jpg",
            "price": 28.00,
            "price_view": "28,00",
            "color": [ 1, 2, 3, 5, 8 ],
            "size": [ 1, 2, 4, 7, 10 ],
            "until": "3",
            "until_price": "9,33",
        }, {
            "id": 2,
            "name": "saia em couro",
            "image": "img_3.jpg",
            "price": 398.00,
            "price_view": "398,00",
            "color": [ 3, 4, 6, 7, 9 ],
            "size": [ 2, 4, 5, 6, 11 ],
            "until": "5",
            "until_price": "30,00",
        }, {
            "id": 3,
            "name": "cardigan tigre",
            "image": "img_4.jpg",
            "price": 398.00,
            "price_view": "398,00",
            "color": [ 1, 2, 3, 4, 6, 8, 10 ],
            "size": [ 1, 4, 7, 8, 10, 11 ],
            "until": "5",
            "until_price": "30,00",
        }, {
            "id": 4,
            "name": "cardigan off white",
            "image": "img_5.jpg",
            "price": 99.90,
            "price_view": "99,90",
            "color": [ 2, 3, 4, 5, 6, 7, 8, 9 ],
            "size": [ 1, 2, 5, 7, 9, 11 ],
            "until": "3",
            "until_price": "33,30",
        }, {
            "id": 5,
            "name": "body leopardo",
            "image": "img_6.jpg",
            "price": 129.90,
            "price_view": "129,90",
            "color": [ 1, 2, 4, 7, 9, 10 ],
            "size": [ 2, 5, 6, 7, 9, 11 ],
            "until": "3",
            "until_price": "43,43",
        }, {
            "id": 6,
            "name": "casaco pelos",
            "image": "img_7.jpg",
            "price": 398.00,
            "price_view": "398,00",
            "color": [ 1, 2, 4, 6, 8, 10 ],
            "size": [ 1, 2, 3, 5, 7, 9, 10, 11 ],
            "until": '5',
            "until_price": "30,00",
        }, {
            "id": 7,
            "name": "cropped stripes",
            "image": "img_8.jpg",
            "price": 120.00,
            "price_view": "120,00",
            "color": [ 2, 3, 4, 6, 7, 9, 10 ],
            "size": [ 2, 3, 4, 7, 8, 10 ],
            "until": "3",
            "until_price": "40,00",
        }, {
            "id": 8,
            "name": "camisa transparente",
            "image": "img_9.jpg",
            "price": 398.00,
            "price_view": "398,00",
            "color": [ 1, 2, 3, 4, 7, 9, 10 ],
            "size": [ 2, 3, 4, 6, 7, 9, 10, 11 ],
            "until": "5",
            "until_price": "30,00",
        }, {
            "id": 9,
            "name": "pochete clutch",
            "image": "img_10.jpg",
            "price": 99.00,
            "price_view": "99,00",
            "color": [ 1, 2, 5, 6, 8, 9 ],
            "size": [ 1, 2, 3, 4, 5, 8, 11 ],
            "until": "3",
            "until_price": "33,00",
        },
    ]
};